from app.analytics.whi.calculator import whi_calculator
from app.analytics.whi.thresholds import whi_thresholds
from app.analytics.incidents.detector import incident_detector
from app.analytics.incidents.debouncer import incident_debouncer
from app.analytics.incidents.classifier import incident_classifier
from app.analytics.incidents.aggregator import incident_aggregator
from app.analytics.alerts.rules import alert_rules
from app.analytics.alerts.dispatcher import alert_dispatcher
from app.analytics.anomaly.detector import anomaly_detector
from app.analytics.occupancy.analyzer import occupancy_analyzer
from app.analytics.air_quality.analyzer import air_quality_analyzer
from app.analytics.consumables.analyzer import consumables_analyzer
from app.analytics.trends.calculator import trends_calculator
from app.analytics.prediction.placeholder import ml_maintenance_predictor
from app.analytics.floor.aggregator import floor_aggregator
from app.analytics.terminal.aggregator import terminal_aggregator
from app.analytics.airport.aggregator import airport_aggregator
